Feature/#32 message component
Kyutech-C3/OC_2023_frontend pull request #121
Opened 2023-07-05 01:55 UTC by Sea10wood

2023-07-05 02:01 UTC, Sea10wood commented
コミットメッセージの命名規則まちがえました。すみません。

2023-07-05 05:24 UTC, tosaken1116 requested changes

2023-07-05 05:24 UTC, tosaken1116 commented on src/components/Web/MessageTitle/MessageTitle.tsx
> +        <>
レイアウトが崩れてるので<Stack>コンポーネントを使って`direction="row"`を設定して文字が横に並ぶようにしてください

<img width="259" alt="スクリーンショット 2023-07-05 14 23 49" src="https://github.com/Kyutech-C3/OC_2023_frontend/assets/94045195/6ee7039e-565f-46e2-bda4-d1dbe2bb38ab">

2023-07-05 05:26 UTC, tosaken1116 requested changes
2点の修正点以外は完璧です

2023-07-05 05:26 UTC, tosaken1116 commented on src/components/Web/MessageTitle/MessageTitle.tsx
> +                <Typography
fontWeightをつけて文字を太くしてください

2023-07-06 04:33 UTC, tosaken1116 requested changes
もちっとだけ修正お願いします

2023-07-06 04:33 UTC, tosaken1116 commented on src/components/Web/MessageTitle/MessageTitle.tsx
> +            {characters.map(({ char, color, fontSize,fontWeight }, index) => (
存在しないpropsを渡しているのでbuildエラーが出てます

2023-07-06 04:33 UTC, tosaken1116 commented on src/components/Web/MessageTitle/MessageTitle.tsx
>                      style={{
muiのTypographyなのでstyleではなくsxで渡してください

2023-07-08 05:33 UTC, tosaken1116 approved these changes

2023-07-08 05:33 UTC, merged